# Workflow to upload APIs to docs staging environment 

name: Sync OpenAPI definition to ReadMe staging 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
          
      # Update NFT API in docs
      - name: GitHub action to update NFT API
        uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi nft/nfts.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.NFT_API_ID }}
      
      # Update Notify API in docs
      - name: GitHub action to update Notify API
        uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi notify/notify.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.NOTIFY_API_ID }}
      
      # Update SDK docs 
      - name: GitHub action to update SDK APIs
        uses: readmeio/rdme@7.5.0
        with:
          rdme: openapi sdk/sdk.yaml --key=${{ secrets.README_API_KEY }} --id=${{ secrets.SDK_API_ID }}
